### ISSUE TITLE
As mytiki.com, I want to host a centralized metadata catalog, so that I can manage multiple deployed data lakes

### ISSUE THREAD

**Issue by mike-audi** [tiki-bar/tiki-ocean-catalog#77]
### Acceptance Criteria

- [ ] A deployable glue data catalog
- [ ] A deployable lake formation configuration
- [ ] A SAR application to deploy the catalog in any mytiki account

### Tasks

- [ ] move to private repo in tiki 
- [ ] CF template for glue and lake formation
- [ ] SAR application with org visibility
