### ISSUE TITLE
As mytiki.com, I want to design a deployable lake registration, so that lakes can be attached to the central catalog

### ISSUE THREAD

**Issue by mike-audi** [tiki-bar/tiki-ocean-catalog#78]
### Acceptance Criteria

- [ ] Register lake with central catalog
- [ ] Auto register on deployment

### Tasks

- [ ] Design registration system
- [ ] Scope registration system
- [ ] Create dependent stories
